#This is the file Google App Engine uses for deployment. Update the cloud_sql_instances: <INSTANCE_CONNECTION_NAME> with
#the connection string you find in your Cloud SQL Instance. See the documentation for more information
#https://cloud.google.com/sql/docs/mysql/connect-app-engine
runtime: nodejs

env: flexible

env_variables:
  NODE_ENV: production

beta_settings:
  cloud_sql_instances: <INSTANCE_CONNECTION_NAME>
